name: 'Build and push'

on:
  push:
    branches:
      - dev
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Set image tag and name'
        id: tag
        run: |
          IMAGE_TAG="master"
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            REF=${{ github.ref }};
            TAG_FULL=${REF#refs/*/};
            IMAGE_TAG=${TAG_FULL//\//_};
          fi
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "image_name=${{ secrets.IMAGE_NAME }}" >> $GITHUB_OUTPUT

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2

      - name: 'Build and push dev'
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{steps.tag.outputs.image_name}}:${{steps.tag.outputs.image_tag}}
